[package]
name = "ask-cli"
version = "0.1.1"
authors = ["Alex Saveau <saveau.alexandre@gmail.com>"]
edition = "2021"
description = "Ask CLI offers a simple way to ask a yes or no question."
repository = "https://github.com/SUPERCILEX/ask-cli"
keywords = ["cli", "answer", "ask", "question", "prompt"]
categories = ["command-line-utilities"]
license = "Apache-2.0"

[dev-dependencies]
goldenfile = "1.4.5"
public-api = "0.22.0"
rustdoc-json = "0.6.0"
trycmd = "0.14.4"

[[bin]]
name = "ask"
path = "src/main.rs"

[profile.release]
lto = true
codegen-units = 1
strip = true
panic = "abort"
